import { Project, Experience, Technology } from './types';

export const PROJECTS: Project[] = [
  {
    id: 9,
    title: 'BlockInventory',
    description: 'A blockchain-powered inventory system built in Java with MongoDB, providing secure and transparent product tracking.',
    image: '/images/block-inventory.png',
    tags: ['Java', 'MongoDB', 'Blockchain', 'Inventory Management'],
    link: '#',
    year: '2023',
  },
  {
    id: 11,
    title: 'AlmobaraConcourseFinder',
    description: 'A PHP/MySQL-based web app that helps Moroccan students explore past concours by school and year.',
    image: './images/almobara.png',
    tags: ['PHP', 'MySQL', 'JavaScript', 'XAMPP'],
    link: '#',
    year: '2023',
  },
  {
    "id": 13,
    "title": "Real Estate Website",
    "description": "A modern real estate website built with React, featuring a sleek UI, property listings, and reusable components, developed by following Zainkeepscode's tutorial.",
    "image": "/images/real-estate.png",
    "tags": ["React", "HTML5", "CSS3", "JavaScript", "Vite", "React Icons"],
    "link": "https://github.com/MOHAJII/Real-Estate-website",
    year: '2024',
  },
  {
    id: 1,
    title: 'TetriLogic Challenge',
    description: 'A Tetris-inspired C++ game using SDL2 where players align shapes of the same color or form to score, with increasing complexity across levels.',
    image: './images/tetri-logic.png',
    tags: ['C++', 'SDL2', 'OOP', 'Game Loop'],
    link: '#',
    year: '2023',
  },
  {
    id: 4,
    title: 'SmartRed (IoT Traffic Light)',
    description: 'A basic Arduino-based traffic light system simulating real-world signal logic with LEDs and timing cycles.',
    image: './images/smart-red.png',
    tags: ['Arduino', 'Embedded Systems', 'Tinkercad', 'Traffic Simulation'],
    link: '#',
    year: '2023',
  },
  {
    id: 5,
    title: 'VMQuickCreate',
    description: 'An automation tool using Bash and PowerShell to rapidly create virtual machines on Windows via WSL and Hyper-V.',
    image: './images/vm-quick-create.png',
    tags: ['Bash', 'PowerShell', 'WSL', 'Hyper-V'],
    link: '#',
    year: '2023',
  },
  {
    id: 6,
    title: 'IMC Calculator',
    description: 'An Android app for calculating BMI with a clean UI built in XML and backend logic in Java, no database required.',
    image: './images/imc-calculator.png',
    tags: ['Java', 'Android', 'XML', 'Mobile App'],
    link: 'https://github.com/MOHAJII/IMC-Calculator-Android',
    year: '2025',
  },
  {
    id: 7,
    title: 'ExprCompiler',
    description: 'A Java-based mini compiler that parses and evaluates mathematical/logical expressions using recursive descent parsing.',
    image: './images/expr-compiler.png',
    tags: ['Java', 'Compiler Design', 'Parsing', 'IDEA'],
    link: '#',
    year: '2023',
  },
  {
    id: 8,
    title: 'Edutris',
    description: 'A C++ CLI game blending Moroccan culture and Tetris mechanics, combining trivia questions and word-building gameplay.',
    image: './images/edutris.png',
    tags: ['C++', 'CLI', 'Culture Trivia', 'Game Logic'],
    link: '#',
    year: '2023',
  },
  {
    id: 3,
    title: 'Snoopy Quest',
    description: 'A terminal-based C game where players help Snoopy navigate a maze, collect rewards, and avoid obstacles, using basic data structures.',
    image: './images/snoopy-quest.png',
    tags: ['C', 'CLI Game', 'Data Structures'],
    link: '#',
    year: '2023',
  },
  {
    id: 10,
    title: 'BinToSource',
    description: 'A reverse engineering project that decompiles and rebuilds a Java application from class files using IntelliJ tools.',
    image: './images/bin-to-source.png',
    tags: ['Java', 'Reverse Engineering', 'Decompiler'],
    link: '#',
    year: '2023',
  },
  {
    id: 2,
    title: 'SortRace',
    description: 'A CLI tool in C that benchmarks various sorting algorithms and visualizes their performance in real time using Plotlib.',
    image: './images/sort-race.png',
    tags: ['C', 'Sorting Algorithms', 'Plotlib'],
    link: '#',
    year: '2023',
  },
  {
    "id": 12,
    "title": "Age Calculator Web Application",
    "description": "A beginner-friendly web app that calculates a user's exact age in years, months, and days. Built using HTML, CSS, and JavaScript to demonstrate DOM manipulation and form validation.",
    "image": "./images/age-calc.png",
    "tags": ["HTML5", "CSS3", "JavaScript"],
    "link": "https://github.com/MOHAJII/age-calculator-web-site",
    year: '2024',
  },  
 
];



export const EXPERIENCES: Experience[] = [
  {
    id: 1,
    title: 'Senior Software Engineer',
    company: 'Tech Innovations Inc.',
    duration: '2021 - Present',
    description: 'Leading development of scalable web applications and mentoring junior developers.',
  },
  {
    id: 2,
    title: 'Full Stack Developer',
    company: 'Digital Solutions LLC',
    duration: '2019 - 2021',
    description: 'Developed and maintained various client projects using modern web technologies.',
  },
  {
    id: 3,
    title: 'Frontend Developer',
    company: 'Creative Web Agency',
    duration: '2017 - 2019',
    description: 'Created responsive user interfaces and implemented complex UI interactions.',
  },
];

export const TECHNOLOGIES: Technology[] = [
  {
    id: 1,
    name: 'JavaScript',
    icon: 'code',
  },
  {
    id: 2,
    name: 'TypeScript',
    icon: 'code-2',
  },
  {
    id: 3,
    name: 'React',
    icon: 'component',
  },
  {
    id: 4,
    name: 'Node.js',
    icon: 'server',
  },
  {
    id: 5,
    name: 'MongoDB',
    icon: 'database',
  },
  {
    id: 6,
    name: 'AWS',
    icon: 'cloud',
  },
];